---
title: "Pull weather from weatherunderground"
author: "Jake"
date: "April 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown
```{r}
suppressPackageStartupMessages(library(rwunderground))
set_api_key("5ee8e25053049549")
set_location(zip_code = "04616")
```






```{r}


#2006

 day_20061125 <-history_daily(set_location(zip_code = "04616") , date = 20061125 )
day_20061126 <-history_daily(set_location(zip_code = "04616") , date = 20061126 )
 day_20061202 <-history_daily(set_location(zip_code = "04616") , date = 20061202 )
  day_20061203 <-history_daily(set_location(zip_code = "04616") , date = 20061203 )
   day_20061209 <-history_daily(set_location(zip_code = "04616") , date = 20061209 )
      day_20061210 <-history_daily(set_location(zip_code = "04616") , date = 20061210 )
         day_20061216 <-history_daily(set_location(zip_code = "04616") , date = 20061216 ) 
        
         

   #2007
           
   
 day_20071201 <-history_daily(set_location(zip_code = "04616") , date = 20071201 )
  day_20071202 <-history_daily(set_location(zip_code = "04616") , date = 20071202 )
 
 day_20071208 <-history_daily(set_location(zip_code = "04616") , date = 20071208 )
  day_20071209 <-history_daily(set_location(zip_code = "04616") , date = 20071209 )

   day_20071215 <-history_daily(set_location(zip_code = "04616") , date = 20071215 )
  day_20071216 <-history_daily(set_location(zip_code = "04616") , date = 20071216 )
  
  #2008
  
   day_20081129 <-history_daily(set_location(zip_code = "04616") , date = 20081129 )
  day_20081130 <-history_daily(set_location(zip_code = "04616") , date = 20081130 )
  
     day_20081206 <-history_daily(set_location(zip_code = "04616") , date = 20081206 )
  day_20081207 <-history_daily(set_location(zip_code = "04616") , date = 20081207 )
  
      day_20081213 <-history_daily(set_location(zip_code = "04616") , date = 20081213 )
  day_20081214 <-history_daily(set_location(zip_code = "04616") , date = 20081214 )
  
     day_20081220 <-history_daily(set_location(zip_code = "04616") , date = 20081220 )
     
     
     
       #2009
     
      day_20091205 <-history_daily(set_location(zip_code = "04616") , date = 20091205 )
  day_20091206 <-history_daily(set_location(zip_code = "04616") , date = 20091206 )
  
  day_20091212 <-history_daily(set_location(zip_code = "04616") , date = 20091212 )
  day_20091213 <-history_daily(set_location(zip_code = "04616") , date = 20091213 )
     
     
     #2010
  
  
   day_20101204 <-history_daily(set_location(zip_code = "04616") , date = 20101204 )
  day_20101205 <-history_daily(set_location(zip_code = "04616") , date = 20101205 )
  
  day_20101211 <-history_daily(set_location(zip_code = "04616") , date = 20101211 )
  day_20101212 <-history_daily(set_location(zip_code = "04616") , date = 20101212 )
  
  #20 eleven
  
   day_20111203 <-history_daily(set_location(zip_code = "04616") , date = 20111203 )
  day_20111204 <-history_daily(set_location(zip_code = "04616") , date = 20111204 )
  
  day_20111210 <-history_daily(set_location(zip_code = "04616") , date = 20111210 )
  day_20111211 <-history_daily(set_location(zip_code = "04616") , date = 20111211 )
  
    day_20111217 <-history_daily(set_location(zip_code = "04616") , date = 20111217 )
  
     
    #20 twekve
    
    day_20121201 <-history_daily(set_location(zip_code = "04616") , date = 20121201 )
     day_20121202 <-history_daily(set_location(zip_code = "04616") , date = 20121202)
     
  day_20121208 <-history_daily(set_location(zip_code = "04616") , date = 20121208 )
     day_20121209 <-history_daily(set_location(zip_code = "04616") , date = 20121209 )
  
      day_20121215 <-history_daily(set_location(zip_code = "04616") , date = 20121215 )
     day_20121216 <-history_daily(set_location(zip_code = "04616") , date = 20121216 )

# 20 thirteen
     
     day_20131130 <-history_daily(set_location(zip_code = "04616") , date = 20131130 )
     day_20131201 <-history_daily(set_location(zip_code = "04616") , date = 20131201)
     
          day_20131206 <-history_daily(set_location(zip_code = "04616") , date = 20131206)
        day_20131207 <-history_daily(set_location(zip_code = "04616") , date = 20131207)
        
        day_20131214 <-history_daily(set_location(zip_code = "04616") , date = 20131214)
        day_20131215 <-history_daily(set_location(zip_code = "04616") , date = 20131215)
        
        #20 fourteen
        
        day_20141129 <-history_daily(set_location(zip_code = "04616") , date = 20141129 )
     day_20141130 <-history_daily(set_location(zip_code = "04616") , date = 20141130 )
     
     day_20141206 <-history_daily(set_location(zip_code = "04616") , date = 20141206 )
     day_20141207 <-history_daily(set_location(zip_code = "04616") , date = 20141207 )
     
      day_20141213 <-history_daily(set_location(zip_code = "04616") , date = 20141213 )
     day_20141214 <-history_daily(set_location(zip_code = "04616") , date = 20141214 )
     
     #20 fifteen
     
day_20151128 <-history_daily(set_location(zip_code = "04616") , date = 20151128 )
day_20151129 <-history_daily(set_location(zip_code = "04616") , date = 20151129 ) 

    
day_20151205 <-history_daily(set_location(zip_code = "04616") , date = 20151205 )
day_20151206 <-history_daily(set_location(zip_code = "04616") , date = 20151206 ) 

day_20151212 <-history_daily(set_location(zip_code = "04616") , date = 20151212 )
day_20151213 <-history_daily(set_location(zip_code = "04616") , date = 20151213 )

#20 sixteen

day_20161126 <-history_daily(set_location(zip_code = "04616") , date = 20161126 )
day_20161127 <-history_daily(set_location(zip_code = "04616") , date = 20161127 ) 

    
day_20161203 <-history_daily(set_location(zip_code = "04616") , date = 20161203 )
day_20161204 <-history_daily(set_location(zip_code = "04616") , date = 20161204 ) 


day_20161210 <-history_daily(set_location(zip_code = "04616") , date = 20161210 )
day_20161211 <-history_daily(set_location(zip_code = "04616") , date = 20161211 )


day_20161217 <-history_daily(set_location(zip_code = "04616") , date = 20161217 )
day_20161218 <-history_daily(set_location(zip_code = "04616") , date = 20161218 )

     #20 seventeen


day_20171125 <-history_daily(set_location(zip_code = "04616") , date = 20171125 )
day_20171126 <-history_daily(set_location(zip_code = "04616") , date = 20171126 )

day_20171202 <-history_daily(set_location(zip_code = "04616") , date = 20171202 )
day_20171203 <-history_daily(set_location(zip_code = "04616") , date = 20171203 ) 


day_20171209 <-history_daily(set_location(zip_code = "04616") , date = 20171209 )
day_20171210 <-history_daily(set_location(zip_code = "04616") , date = 20171210 ) 



day_20171216 <-history_daily(set_location(zip_code = "04616") , date = 20171216 )
day_20171217 <-history_daily(set_location(zip_code = "04616") , date = 20171217 ) 


table <- rbind(day_20061125 , day_20061126 ,day_20061202, day_20061203, day_20061209, day_20061210, day_20061216, #
               day_20071201, day_20071202, day_20071208, day_20071209, day_20071215, day_20071216, day_20081129, day_20081130, day_20081206, day_20081207, day_20081213, day_20081214, day_20081220,  day_20091205 , day_20091206, day_20091212 , day_20091213, day_20101204, day_20101205, day_20101211,
               day_20101212 , day_20111203 , day_20111204, day_20111210, day_20111211, day_20111217 , day_20121201, day_20121202, day_20121208, day_20121209, day_20121215, day_20121216, day_20131130, day_20131201, day_20131206 , day_20131207
    , day_20131214, day_20131215 , day_20141129, day_20141130, day_20141206, day_20141207, day_20141213, day_20141214, day_20151128, 
    day_20151129, day_20151205, day_20151206, day_20151212, day_20151213, day_20161126, day_20161127, day_20161203, day_20161204, day_20161210
    , day_20161211, day_20161217, day_20161218,day_20171125, day_20171126, day_20171202, day_20171203, day_20171209, day_20171210, day_20171216, day_20171217)
     

weather <- table %>% 
  select(precip , max_wind_spd , max_temp,
min_temp, mean_wind_spd  , mean_temp ,
fog, rain, snow, date)
```







```{r}

day_20171210 <-history(set_location(zip_code = "04616") , date = 20171210)

# 
 day_20171210 <-history_daily(set_location(zip_code = "04616") , date = 20171210)
# 
# 
# few_days <- history_range(set_location(zip_code = "04616") , date_start = "20051119" , 
#             date_end = "20051127" ,limit = 10 )
```


```{r}

#cat <- gsub("-","", series$Date)


#days <-history_daily(set_location(zip_code = "04616") , date = 20051119)

#tree_sales_dates<- list("20051120" , "20061120"  , "20071120")

sales_dates <- gsub("-","", series$Date)

pull_weather <- function(x) { {
date <- history_daily(set_location(zip_code = "04616") , date = x )
Sys.sleep(6.2)
}
  date$chardate <- x

 return(data <- print(date))
} 

weather_historyz <- data.frame(sapply(sales_dates  , pull_weather))


#hh <-  sapply(tree_sales_dates  , pull_weather)



df <- data.frame(matrix(unlist(weather_historyz), nrow=93, byrow=T))


df <- data.frame(matrix(unlist(weather_historyz), nrow=50, byrow=F))


dogd<- parse_datetime(df[,1])



dog <- union(jake[1] , jake[2])

```








```{r}

working_series <- series %>% filter(Date > "2006-01-01" )

sales_dates2 <- gsub("-","", working_series$Date)



#######################################



pull_weather <- function(x) { {
date <- history_daily(set_location(zip_code = "04616") , date = x )
Sys.sleep(6.2)
}
  date$chardate <- x

 return(data <- print(date))
} 

weather_historyz <- data.frame(sapply(sales_dates2 , pull_weather))


```


```{r}

library(quantmod)


series_name <- "UNRATE"

# Load the data using getSymbols
getSymbols(series_name, src = "FRED")




library(Quandl)

# Create a quandl_code object
quandl_code <- "FRED/UNRATE"

# Load the data using Quandl
unemploy_rate <- Quandl(quandl_code)

```



